version: "3.9"

services:
  node:
    image: node      
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=development      
    working_dir: /home/node/app
    volumes:
      # - ${PWD}:/app      
      - ./:/home/node/app
      # - .:.      
    ports:
      - "3000:3000"
      - "443:443"
    restart: unless-stopped
    # entrypoint: tail -F /dev/null
    entrypoint: node index
    # user: root    